---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines 
- name: pivnet-opsmgr

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/upload-opsman/task.sh
