platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines

params:
  PIPELINE_NAME:
  PIPELINE_PATH:
  PIPELINE_PARAMS:
  ATC_EXTERNAL_URL:
  ATC_BASIC_AUTH_USERNAME:
  ATC_BASIC_AUTH_PASSWORD:
  ATC_TEAM_NAME:

run:
  path: pcf-pipelines/tasks/set-pipeline/task.sh
