---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
  - name: unpatched-release
  - name: pcf-pipelines
outputs:
  - name: patched-release

params:
  PIPELINE_FILE:
  PATCH_FILES:

run:
  path: pcf-pipelines/ci/tasks/apply-patch/task.sh
