---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: czero/cflinuxfs2
 
inputs:
- name: tarball

outputs:
- name: unpacked_tarball

run: 
 path: sh
 args:
 - -c
 - |
   tar -C unpacked_tarball -xvf tarball/*.tgz
