---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

outputs:
  - name: update_ert_config

params:
  PIVNET_TOKEN:
  OPSMAN_ADMIN_USERNAME:
  OPSMAN_ADMIN_PASSWORD:
  OPSMAN_URI:
  IAAS_TYPE:
  PIVNET_POLL_INTERVAL:
  OPSMAN_TIMEOUT_SECONDS:
  CF_API_URI:
  CF_USER:
  CF_PASSWORD:
  OPSMAN_MAJOR_MINOR_VERSION:
  CHECK_NEW_OPSMAN_EVERY:

run:
  path: bash
  args:
  - -ce
  - |
    cat > update_ert_config/params.yml <<EOF
      cf_api_uri: "${CF_API_URI}"
      cf_password: "${CF_PASSWORD}"
      cf_user: "${CF_USER}"
      check_new_opsman_every: "${CHECK_NEW_OPSMAN_EVERY}"
      iaas_type: "${IAAS_TYPE}"
      opsman_admin_password: "${OPSMAN_ADMIN_PASSWORD}"
      opsman_admin_username: "${OPSMAN_ADMIN_USERNAME}"
      opsman_major_minor_version: "${OPSMAN_MAJOR_MINOR_VERSION}"
      opsman_passphrase: "${OPSMAN_ADMIN_PASSWORD}"
      opsman_timeout_seconds: "${OPSMAN_TIMEOUT_SECONDS}"
      opsman_uri: "${OPSMAN_URI}"
      pivnet_poll_interval: "${PIVNET_POLL_INTERVAL}"
      pivnet_token: "${PIVNET_TOKEN}"
      tile_upload_timeout: 1800
    EOF
