---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
    tag: latest

outputs:
- name: config

params:
  CONFIG:

run:
  path: bash
  args:
  - -c
  - |
    IFS=$'\n'
    for line in $CONFIG; do
      echo "$line" >> config/params.yml
    done
