---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: pcf-pipelines
- name: cf-cli
- name: om
- name: version

outputs:
- name: pcf-pipelines-release-files

run:
  path: sh
  args:
  - -ce
  - |
    version=v$(cat version/version)

    tar --extract --file cf-cli/*.tgz

    mv om/om-linux .

    echo "pinning pipeline params to current version..."
    find ./pcf-pipelines -type f -name "params.yml" -exec sed -i s/__PIPELINE_VERSION_COMPATIBILITY__/${version}/g {} +

    tar \
      --exclude .git* \
      --exclude ci \
      --exclude "*.go" \
      --create \
      --gzip \
      --file pcf-pipelines-release-files/pcf-pipelines-$version.tgz \
      pcf-pipelines \
      cf \
      om-linux
