platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git

inputs:
- name: pcf-pipelines
- name: version

outputs:
- name: stamped-pcf-pipelines

run:
  path: bash
  args:
  - -ce
  - |
    export HOME=$PWD

    git config --global user.name "CI Bot"
    git config --global user.email "c0-coreteam+pcf-pipelines-ci@pivotal.io"

    git clone pcf-pipelines stamped-pcf-pipelines

    version=v$(cat version/version)

    files=$(find stamped-pcf-pipelines -type f -name pipeline.yml -exec grep -l "pcf-pipelines-tarball" {} \;)
    for f in "${files[@]}"; do
      sed -i "/product_slug: pcf-automation/ {N; s/\(product_slug: pcf-automation.*product_version: \).*/\1${version}/g}" $f
    done

    cd stamped-pcf-pipelines

    git add -A
    git commit --file - <<EOF
    Bump pcf-pipelines-tarball version to ${version}
    EOF
