---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: pcf-pipelines

run:
  path: bash
  args:
  - -ce
  - |
    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    go get github.com/onsi/ginkgo
    go get github.com/onsi/gomega
    go get gopkg.in/yaml.v2
    go get github.com/concourse/atc

    go install github.com/onsi/ginkgo/ginkgo

    pushd pcf-pipelines
      ginkgo -p -r -randomizeAllSpecs
    popd
