---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: pcf-pipelines
- name: atc
  path: go/github.com/concourse/atc
- name: ginkgo
  path: go/github.com/onsi/ginkgo
- name: gomega
  path: go/github.com/onsi/gomega
- name: yaml
  path: go/github.com/gopkg.in/yaml.v2

run:
  path: bash
  args:
  - -ce
  - |
    go install github.com/onsi/ginkgo/ginkgo

    pushd pcf-pipelines
      ginkgo -p -r -randomizeAllSpecs
    popd
