---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

inputs:
- name: pcf-pipelines

params:
  PIPELINE_NAME:
  PIPELINE_PATH:
  PIVNET_TOKEN:
  OPSMAN_ADMIN_USERNAME:
  OPSMAN_ADMIN_PASSWORD:
  OPSMAN_URI:
  GITHUB_TOKEN:
  IAAS_TYPE:
  PIVNET_POLL_INTERVAL:
  OPSMAN_TIMEOUT_SECONDS:
  ATC_EXTERNAL_URL:
  ATC_BASIC_AUTH_USERNAME:
  ATC_BASIC_AUTH_PASSWORD:

run:
  path: bash
  args:
  - -ce
  - |
    curl \
      --silent \
      --insecure \
      --output fly \
      "${ATC_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"

    chmod +x fly

    ./fly --target self login \
      --insecure \
      --concourse-url "${ATC_EXTERNAL_URL}" \
      --username "${ATC_BASIC_AUTH_USERNAME}" \
      --password "${ATC_BASIC_AUTH_PASSWORD}" \
      --team-name "${ATC_TEAM_NAME}"

    cat > params.yml <<EOF
      pivnet_token: "${PIVNET_TOKEN}"
      opsman_admin_username: "${OPSMAN_ADMIN_USERNAME}"
      opsman_admin_password: "${OPSMAN_ADMIN_PASSWORD}"
      opsman_uri: "${OPSMAN_URI}"
      github_token: "${GITHUB_TOKEN}"
      iaas_type: "${IAAS_TYPE}"
      pivnet_poll_interval: "${PIVNET_POLL_INTERVAL}"
      opsman_timeout_seconds: "${OPSMAN_TIMEOUT_SECONDS}"
      cf_api_uri: "${CF_API_URI}"
      cf_user: "${CF_USER}"
      cf_password: "${CF_PASSWORD}"
      check_new_opsman_every: "${CHECK_NEW_OPSMAN_EVERY}"
      opsman_major_minor_version: "${OPSMAN_MAJOR_MINOR_VERSION}"
      upgrade_opsman_aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
      upgrade_opsman_aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
      upgrade_opsman_aws_region: "${AWS_REGION}"
      upgrade_opsman_aws_vpc_id: "${AWS_VPC_ID}"
      upgrade_opsman_existing_opsman_vm_name: "${EXISTING_OPSMAN_VM_NAME}"
    EOF

    ./fly --target self set-pipeline \
      --non-interactive \
      --pipeline ${PIPELINE_NAME} \
      --config ${PIPELINE_PATH} \
      --load-vars-from params.yml
