---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines 
- name: tool-om

params:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/deploy-director/task.sh
