---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  SYSLOG_HOST:
  SYSLOG_PORT:
  BACKUPS_SCP_HOST:
  BACKUPS_SCP_PORT:
  BACKUPS_SCP_USER:
  BACKUPS_SCP_KEY:
  BACKUPS_SCP_DESTINATION:
  BACKUPS_SCP_TIMEOUT:
  BACKUPS_CRON_SCHEDULE:
  DISABLE_TLS:  

inputs:
  - name: pcf-pipelines
  - name: tool-om

run:
  path: pcf-pipelines/tasks/config-redis/task.sh
