---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: tool-om

params:
  ERT_DOMAIN:
  OPSMAN_USER:
  OPSMAN_PASSWORD:

run:
  path: pcf-pipelines/tasks/install-pcf-aws/config-opsman.sh
