---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/rootfs}

inputs:
  - name: pcf-pipelines

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: pcf-pipelines/tasks/stage-and-apply-updates/task.sh
