---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: tool-om

params:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:

run:
  path: pcf-pipelines/tasks/install-pcf-aws/deploy-director/task.sh
