---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: pcf-pipelines
  - name: terraform-state
params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  AWS_KEY_NAME:
  PEM:
  AWS_REGION:
  S3_ENDPOINT:
  TRUSTED_CERTIFICATES:
  ert_subnet_reserved_ranges_z1:
  ert_subnet_reserved_ranges_z2:
  ert_subnet_reserved_ranges_z3:
  services_subnet_reserved_ranges_z1:
  services_subnet_reserved_ranges_z2:
  services_subnet_reserved_ranges_z3:
  dynamic_services_subnet_reserved_ranges_z1:
  dynamic_services_subnet_reserved_ranges_z2:
  dynamic_services_subnet_reserved_ranges_z3:
  infra_subnet_reserved_ranges_z1:
run:
  path: pcf-pipelines/install-pcf/aws/tasks/config-director/task.sh
