platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines

params:
  ATC_EXTERNAL_URL:
  ATC_TEAM_NAME:
  ATC_BASIC_AUTH_USERNAME:
  ATC_BASIC_AUTH_PASSWORD:
  JOBS:

run:
  path: pcf-pipelines/tasks/trigger-jobs/task.sh
