---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
  - name: ami
outputs:
  - name: terraform-state-output
params:
  DB_MASTER_USERNAME:
  DB_MASTER_PASSWORD:
  TERRAFORM_PREFIX:
  aws_access_key_id:
  aws_secret_access_key:
  aws_key_name:
  aws_cert_arn:
  amis_nat:
  aws_region:
  aws_az1:
  aws_az2:
  aws_az3:
  system_domain:
  apps_domain:
  route53_zone_id:
  vpc_cidr:
  public_subnet_cidr_az1:
  public_subnet_cidr_az2:
  public_subnet_cidr_az3:
  ert_subnet_cidr_az1:
  ert_subnet_cidr_az2:
  ert_subnet_cidr_az3:
  services_subnet_cidr_az1:
  services_subnet_cidr_az2:
  services_subnet_cidr_az3:
  dynamic_services_subnet_cidr_az1:
  dynamic_services_subnet_cidr_az2:
  dynamic_services_subnet_cidr_az3:
  infra_subnet_cidr_az1:
  rds_subnet_cidr_az1:
  rds_subnet_cidr_az2:
  rds_subnet_cidr_az3:
  opsman_ip_az1:
  nat_ip_az1:
  nat_ip_az2:
  nat_ip_az3:
  OPSMAN_ALLOW_SSH_CIDR_RANGES:
  OPSMAN_ALLOW_HTTPS_CIDR_RANGES:
run:
  path: pcf-pipelines/install-pcf/aws/tasks/prepare-aws/task.sh
