---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
  - name: tool-om-beta
params:
  ERT_DOMAIN:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  AWS_KEY_NAME:
  PEM:
  AWS_REGION:
  S3_ENDPOINT:
  ert_subnet_reserved_ranges_z1:
  ert_subnet_reserved_ranges_z2:
  ert_subnet_reserved_ranges_z3:
  services_subnet_reserved_ranges_z1:
  services_subnet_reserved_ranges_z2:
  services_subnet_reserved_ranges_z3:
  infra_subnet_reserved_ranges_z1:
run:
  path: pcf-pipelines/tasks/install-pcf-aws/config-director/task.sh
