---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines

params:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OS_PROJECT_ID:
  OS_PROJECT_NAME:
  OS_INTERFACE:
  OS_AUTH_URL:
  OS_PASSWORD:
  OS_USERNAME:
  OS_IDENTITY_API_VERSION:
  OS_USER_DOMAIN_NAME:
  OS_TENANT:
  OS_REGION_NAME:
  OS_NETWORKING_MODEL:
  SECURITY_GROUP:
  KEYPAIR_NAME:
  PRIVATE_KEY:
  IGNORE_SERVER_AZ:
  DISABLE_DHCP:
  VM_PASSWORD_TYPE:
  TRUSTED_CERTIFICATES:
  API_SSL_CERT:
  BOSH_DATABASE_TYPE:
  BOSH_BLOBSTORE_TYPE:
  ICMP_CHECKS_ENABLED:
  AZ_01_NAME:
  NTP_SERVERS:
  METRICS_IP:
  RESURRECTOR_ENABLED:
  MAX_THREADS:
  INFRA_NETWORK:
  INFRA_SUBNET:
  INFRA_DNS:
  INFRA_GATEWAY:
  INFRA_RESERVED_IP_RANGES:
  INFRA_NW_AZS:
  ERT_NETWORK:
  ERT_SUBNET:
  ERT_DNS:
  ERT_GATEWAY:
  ERT_NW_AZS:
  ERT_RESERVED_IP_RANGES:
  SERVICES_NETWORK:
  SERVICES_SUBNET:
  SERVICES_DNS:
  SERVICES_GATEWAY:
  SERVICES_NW_AZS:
  SERVICES_RESERVED_IP_RANGES:
  DYNAMIC_SERVICES_NETWORK:
  DYNAMIC_SERVICES_SUBNET:
  DYNAMIC_SERVICES_DNS:
  DYNAMIC_SERVICES_GATEWAY:
  DYNAMIC_SERVICES_NW_AZS:
  DYNAMIC_SERVICES_RESERVED_IP_RANGES:

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/config-director/task.sh
