---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

inputs:
  - name: pcf-pipelines 
  - name: tool-om
  - name: json_file

run:
  path: pcf-pipelines/tasks/install-ert/configure-ert/task.sh

params:
  pcf_iaas:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
