---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: pcf-pipelines
  - name: opsman-metadata
  - name: terraform-state

outputs:
  - name: terraform-state-output

run:
  path: pcf-pipelines/install-pcf/azure/tasks/create-infrastructure/task.sh

params:
  AZURE_PCF_TERRAFORM_TEMPLATE:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_SERVICE_PRINCIPAL_ID:
  AZURE_SERVICE_PRINCIPAL_PASSWORD:
  AZURE_REGION:
  AZURE_TERRAFORM_PREFIX:
  AZURE_VM_ADMIN:
  AZURE_VM_PASSWORD:
  PCF_ERT_DOMAIN:
  PCF_OPSMAN_ADMIN:
  PCF_OPSMAN_ADMIN_PASSWORD:
  PCF_SSH_KEY_PUB:
  AZURE_MULTI_RESGROUP_NETWORK:
  AZURE_MULTI_RESGROUP_PCF:
  AZURE_MULTI_RESGROUP_INFRA_SUBNET_NAME:
  AZURE_MULTI_RESGROUP_INFRA_VNET_NAME:
  AZURE_TERRAFORM_VNET_CIDR:
  AZURE_TERRAFORM_SUBNET_INFRA_CIDR:
  AZURE_TERRAFORM_SUBNET_ERT_CIDR:
  AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR:
  AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR:
